### ISSUE TITLE
Database reset every time bot crashes

### ISSUE THREAD

**Issue by HavinFiles** [dxnter/lasty#12]
Hey, was just wondering about this. If its only my ID in the database all goes well, but if its trying to function in a server with many users using the bot and it crashes, It'll restart and everyone will have to retype their user in.

Is there a better DB option you could work on like sqlite, mariadb, or mongodb?
Those have been ones I have used in the past very slightly and have seemed to work pretty smooth, I am just not familiar with their formats etc

**Comment by HavinFiles** [comment]
I have always had issues with json databases restarting everytime the bot reboots, so it isnt just your bot its happening with. Its just a struggle you know haha

**Comment by HavinFiles** [comment]
One more thing ive been  looking to do is command aliases, for example, for ",np" (which I had also added ,fm), I would like the command to trigger if I were to say something like "discordfm" for the FM/NP command to come up.

**Comment by dxnter** [comment]
That's strange, I haven't heard of the resetting happening to anyone else before or experienced that. lowdb does have its limits since it's just a JSON file so that may explain why it's crashing.

I initially used MongoDB but I opted for lowdb after a few updates to reduce the installation steps and because it was only storing simple values. In the next version, the database will have way more records so I definitely need to migrate to SQLite.

Command aliases are pretty simple to add, https://github.com/discordjs/Commando-guide/blob/master/using-aliases-in-commands.md unless you mean something different.

Thanks for the suggestions :+1:

**Comment by HavinFiles** [comment]
Yeah SQLite would be insane, it's worked awesome for me in the past I am just not very skilled with it to do stuff like this
But yea of course np for the suggestions 👍 

And if you still have the mongodb version let me know, I'd honestly still be interested in it if u have that previous version
